// // import { AngularEditorConfig } from '@kolkov/angular-editor';
// // import { IAngularMyDpOptions } from 'angular-mydatepicker';

// export const myDatePickerOptions: IAngularMyDpOptions = {
//     dateRange: false,
//     dateFormat: 'dd/mmm/yyyy',
//     firstDayOfWeek: 'mo',
//     sunHighlight: true,
//     markCurrentDay: true,
//     alignSelectorRight: false,
//     openSelectorTopOfInput: false,
//     minYear: 1971,
//     maxYear: 2200,
//     showSelectorArrow: true,
//     monthSelector: true,
//     yearSelector: true,
//     satHighlight: false,
//     highlightDates: [],
//     disableDates: [],
//     disableHeaderButtons: true,
//     showWeekNumbers: false,
//     disableDateRanges: [
//         {
//             begin: { year: 2016, month: 10, day: 5 },
//             end: { year: 2016, month: 10, day: 7 },
//         },
//         {
//             begin: { year: 2016, month: 10, day: 10 },
//             end: { year: 2016, month: 10, day: 12 },
//         },
//     ],
//     disableUntil: {
//         year: new Date().getFullYear(),
//         month: new Date().getMonth() + 1,
//         day: new Date().getUTCDate() - 1,
//     },
//     disableSince: { year: 0, month: 0, day: 0 },
//     disableWeekdays: [],
//     markDates: [],
//     selectorHeight: '266px',
//     selectorWidth: '266px',
//     closeSelectorOnDateSelect: true,
//     closeSelectorOnDocumentClick: true,
//     showMonthNumber: true,
//     appendSelectorToBody: false,
//     focusInputOnDateSelect: false,
//     dateRangeDatesDelimiter: ' - ',
//     showFooterToday: false,
//     rtl: false,
//     stylesData: {
//         selector: '',
//         styles: '',
//     },
// };

// export const editorConfig: AngularEditorConfig = {
//     editable: true,
//     spellcheck: true,
//     height: 'auto',
//     minHeight: '100px',
//     maxHeight: 'auto',
//     width: 'auto',
//     minWidth: '0',
//     translate: 'yes',
//     enableToolbar: true,
//     showToolbar: true,
//     placeholder: 'Enter text here...',
//     defaultParagraphSeparator: '',
//     defaultFontName: '',
//     defaultFontSize: '',
//     fonts: [
//         { class: 'arial', name: 'Arial' },
//         { class: 'times-new-roman', name: 'Times New Roman' },
//         { class: 'calibri', name: 'Calibri' },
//         { class: 'comic-sans-ms', name: 'Comic Sans MS' },
//     ],
//     toolbarHiddenButtons: [
//         [
//             'undo',
//             'redo',
//             'strikeThrough',
//             'subscript',
//             'superscript',
//             'justifyCenter',
//             'justifyRight',
//             'justifyFull',
//             'heading',
//             'textColor',
//             'backgroundColor',
//             'customClasses',
//             'link',
//             'unlink',
//             'insertImage',
//             'insertVideo',
//             'insertHorizontalRule',
//             'removeFormat',
//             'toggleEditorMode',
//         ],
//         [
//             'textColor',
//             'backgroundColor',
//             'customClasses',
//             'link',
//             'unlink',
//             'insertImage',
//             'insertVideo',
//             'insertHorizontalRule',
//             'removeFormat',
//             'toggleEditorMode',
//         ],
//     ],
//     toolbarPosition: 'top',
// };
